name: weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  lottie: ^1.4.1
  geolocator: ^9.0.1
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  http: ^0.13.5
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+4
  equatable: ^2.0.5
  syncfusion_flutter_charts: ^20.2.48
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/day/
    - assets/images/night/

